[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
; On change la méthode d'envoi
upload_protocol = espota
; On donne l'adresse IP du robot
upload_port = 192.168.4.1
